#!/usr/bin/env bash -eu

log() {
	echo "[test] $@"
}

mkdir -p build/logs

log "Generating XML with enketo-transformer reference implementation..."
# TODO

log "Generating XML in Chrome..."
./node_modules/karma/bin/karma start karma.conf.js --single-run \
		--browsers Chrome | tee build/logs/chrome.log
mkdir -p build/generated/chrome
echo '['$(fgrep '[TRANSFORMED]' build/logs/chrome.log | sed -E 's/^.*\[TRANSFORMED\] (.*)'"'"'$/\1,/')'{}]' | node -e '
		var fs = require("fs"),
		    stdin = fs.readFileSync("/dev/stdin").toString(),
		    forms = JSON.parse(stdin);
		forms.forEach(function(form) {
			if(!form.name) return;
			console.log("Processing: " + form.name);
			fs.writeFileSync("build/generated/chrome/" + form.name + ".html.xml", form.content.html);
			fs.writeFileSync("build/generated/chrome/" + form.name + ".model.xml", form.content.model);
		});'

exit 0 # FIXME

log "Generating XML in Firefox..."
./node_modules/karma/bin/karma start karma.conf.js --single-run \
		--browsers Firefox | tee build/logs/firefox.log

set +e
# TODO diff chrome output with enketo-transformer output
# TODO diff firefox output with enketo-transformer output
set -e

# TODO fail build if there are any differences between Chrome/Firefox and reference implementation
