#!/bin/bash -eu
browsers="$@"

log() {
	echo "[compare] $@"
}
diff_xml() {
	local left="$1"
	local right="$2"
	log "====="
	log "= $left vs $right"
	# diff generated output with enketo-transformer output
	diff <(xmllint --format $left) <(xmllint --format $right)
	log "= $left vs $right"
	log "====="
}

log "Comparing generated XML with reference XML..."
set +e
cd reference-xml
for reference in *.html.xml; do
	for browser in $browsers; do
		diff_xml $reference ../build/generated/$browser/$reference
	done
done
for reference in *.model.xml; do
	for browser in $browsers; do
		diff_xml $reference ../build/generated/$browser/$reference
	done
done
set -e
log "Comparison complete."

# TODO fail build if there are any differences between Chrome/Firefox and reference implementation

